### ISSUE TITLE
--terminate flag not working correctly

### ISSUE THREAD

**Issue by gregrahn** [Teradata/tpcds#13]
The `--terminate` flag seems not work as expected.  Looks like you may need to invert the logic and use `--noterminate` since it should terminate by default to match dsdgen defaults.  Currently there seems no way to set it to false given when the flag is present on the command line it is set to `true` state.

If I change the default to `false`, it works correctly, but does not match dsdgen defaults.
https://github.com/Teradata/tpcds/blob/master/src/main/java/com/teradata/tpcds/Options.java#L29

**Comment by petroav** [comment]
@gregrahn thanks for pointing this out! I just put up a pull request addressing this issue https://github.com/Teradata/tpcds/pull/14.
