### ISSUE TITLE
Parent Child Table Row Counts seem wrong

### ISSUE THREAD

**Issue by mcdan** [Teradata/tpcds#26]
I'm probably just not understanding the TPC-DS spec or not understanding the API but why do the row counts not track correctly for tables with children or for the child tables themselves?

For example with scaling set to 1 if if use `TableGenerator.generateTable(Table.CATALOG_SALES)` I get 1441548 rows(!) but if I ask the API: `session.getScaling.getRowCount(Table.CATALOG_SALES)` it says I should have 160000 rows. Tables that are not Parents or children all pass this test.

Can someone explain the discrepancy?

**Comment by rschlussel-zz** [comment]
It's a confusing aspect of how the sales/returns tables (i.e. store_sales, catalog_sales, web_sales) are generated, where the "rowNumber" doesn't mean the actual row number.  Each "rowNumber" for those tables is an order number, and a row gets generated for each item in the order.  so if you were to count the distinct order numbers, you should end up with `session.getScaling.getRowCount()`.  The returns tables are generated from the sales tables, and will only have an entry for a subset of the items in the corresponding sales table (the ones that get returned).

**Comment by mcdan** [comment]
Gotcha - yea the _returns ones as a subset makes sense and I assume there is a certain amount of "randomness" so no way to back into that row count.

Was hoping there was some way to determine the number of rows that should have been generated based on nothing more than the Session details.

**Comment by rschlussel-zz** [comment]
Unfortunately not.  The number of items per order is also generated with "randomness".  There can be anywhere from 8 to 16 items per order.

**Comment by mcdan** [comment]
Thanks! Appreciate the expert opinion.
